export { default as BackToSearch } from './BackToSearch'
export { default as DetailLabel } from './DetailLabel'
export { default as Error } from './Errors'
export { default as GenreDropDown } from './GenreDropDown'
export { default as Header } from './Header'
export { default as LimitSelection } from './LimitSelection'
export { default as Loading } from './Loading'
export { default as MovieCard } from './MovieCard'
export { default as MoviePoster} from './MoviePoster'
export { default as NotFound } from './NotFound'
export { default as Pagination } from './Pagination'
export { default as PeopleSection } from './PeopleSection'
export { default as SearchBar } from './SearchBar'
